spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: 'true'
    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: org.foxbear.mds.*
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
  application:
    name: mds
server:
  port: '8080'
